default:
  image: golang

stages:
  - build
  - test
  - deploy

build:
  stage: build
  artifacts:
      untracked: true
  script:
    - go build
    
test:
  stage: test
  script:
    - PWD=${CI_PROJECT_DIR} go test -race -v ./... -coverprofile=${CI_PROJECT_DIR}/coverage.txt -covermode=atomic
    - ls -l
    - PWD=${CI_PROJECT_DIR} bash <(curl -s https://codecov.io/bash)
    
deploy:
  stage: deploy
  dependencies:
    - build
  only:
    - tags
  script:
    - curl -sL https://git.io/goreleaser | bash
