default:
  image: golang

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - go build
    
test:
  stage: test
  script:
    - go test -race -v ./... -cover
    
deploy:
  stage: deploy
  only:
    - tags
  script:
    - curl -sL https://git.io/goreleaser | bash