default:
  image: golang

stages:
  - build
  - test
  - deploy

build:
  stage: build
  artifacts:
      untracked: true
  script:
    - go build
    
test:
  stage: test
  script:
    - go test -race -v ./... -coverprofile=coverage.txt -covermode=atomic

coverage:
    stage: test
    script:
      - ls -l
      - PWD=${CI_PROJECT_DIR} bash <(curl -s https://codecov.io/bash)
    
deploy:
  stage: deploy
  dependencies:
    - build
  only:
    - tags
  script:
    - curl -sL https://git.io/goreleaser | bash
